### PR TITLE
The guru

### PR DESCRIPTION
**Pull request by ethanmad**
Happy birthday, @jameslennon321!! Pls read diffs

Threw in an extra merge commit to meme up your commit log.

### CODE REVIEW

**Comment by ethanmad** [comment]
🛐 ⛙ 🔜

**Comment by ethanmad** [comment]
💯🔥💩

**Comment by TheSafo** [comment]
Difficult decisions, but merging

**Comment by ethanmad** [comment]
```
 🙏
```

  🙏🙏
🙏🙏🙏

**Pull request merged**
